### ISSUE TITLE
Add Content Sections

### ISSUE THREAD

**Issue by hendrikmolder** [balticsociety/baltsoc#2]
Sections to add:

**Landing Page**
- [x] Vision & Mission
- [x] Short Introduction
- [x] Upcoming Events (with button to Events page)
- [x] Studying in Manchester (with button to static page)

**About Us**
- [x] Introduction
- [x] Committee Members (see #16)

**Events**
- [x] Upcoming Events

**Comment by hendrikmolder** [comment]
Mostly completed, waiting for Robert to write up the content (for non-editable pages).

**TODO**
 - Landing Page (Design + Implementation)

**Comment by hendrikmolder** [comment]
Implemented. Closing.
